# tenants/team-a.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-a
  namespace: argocd
  labels:
    tenant: team-a
    managed-by: platform-team
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      # ✅ Tenant's repo
      repoURL: https://github.com/krisachai/argocd-team-a.git 
      revision: main
      directories:
      - path: 'apps/*'
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/krisachai/argocd-team-a.git
        targetRevision: main
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: team-a
      syncPolicy:
        automated:
          enabled: true
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true