apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-b
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: team-b-project
  source:
    path: 'apps'
    repoURL: https://github.com/krisachai/argocd-team-b.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: team-b
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-b-project
  namespace: argocd # Must be in the Argo CD installation namespace
spec:
  description: Project for team-b
  sourceRepos:
    - '*' 
  destinations:
    - namespace: team-b 
      server: https://kubernetes.default.svc 
  roles:
  - name: team-b-read-only
    description: Read-only privileges to team-b
    policies:
    - p, proj:team-b:team-b-read-only, applications, get, team-b/*, allow
    groups:
    - 123-team-b