apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-b
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: 'apps'
    repoURL: https://github.com/krisachai/argocd-team-b.git
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: team-b
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true